# yaml-language-server: $schema=https://json.schemastore.org/github-action-composite.json
name: "Upload to VPS via SSH"
description: "Upload files to a remote VPS using rsync over SSH"
author: "Slava Hudenko"

runs:
  using: "composite"
  steps:
    - name: Check environment variables
      run: |
        # Confirm VPS_SSH_KEY is set
        if [ -z "${VPS_SSH_KEY:-}" ]; then
        echo "ERROR: VPS_SSH_KEY is not set."
        exit 1
        fi
        # Confirm VPS_HOST is set
        if [ -z "${VPS_HOST:-}" ]; then
        echo "ERROR: VPS_HOST is not set."
        exit 1
        fi
        # Confirm VPS_USER is set
        if [ -z "${VPS_USER:-}" ]; then
        echo "ERROR: VPS_USER is not set."
        exit 1
        fi
        # Confirm VPS_PATH is set
        if [ -z "${VPS_PATH:-}" ]; then
        echo "ERROR: VPS_PATH is not set."
        exit 1
        fi
        # Confirm SRC_PATH is set
        if [ -z "${SRC_PATH:-}" ]; then
        echo "ERROR: SRC_PATH is not set."
        exit 1
        fi

    - name: Load VPS_SSH_KEY into ssh-agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: $VPS_SSH_KEY

    - name: Add VPS_HOST to known_hosts
      shell: bash
      run: |
        set -euo pipefail
        
        # Add host key to known_hosts (more secure than disabling StrictHostKeyChecking)
        ssh-keyscan -H "${VPS_HOST}" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Ensure remote directory exists
      run: |
        set -e
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no "${VPS_USER}@${VPS_HOST}" "mkdir -p ${VPS_PATH}"

    - name: Upload files to VPS via rsync
      run: |
        set -e
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
          --exclude='.git' \
          --exclude='.github' \
          "${SRC_PATH}" "${VPS_USER}@${VPS_HOST}:${VPS_PATH}"
